---
atlas-orca-grids-path:   "~atlas-orca/share/atlas/grids/orca/grids.yaml"
atlas-orca-caching:      false  # Enable runtime caching of data files if not present in atlas-data-path

# Advanced options for development or testing

atlas-orca-validate-uid: false  # Validates uid upon Orca grid creation
atlas-orca-compute-uid:  False  # Recompute uid and ignore encoded uid
...
